### ISSUE TITLE
Fix self-healing for graph-gamedao service

### ISSUE THREAD

**Issue by vovacha** [playzero/zero-network#145]
Fix self-healing with graph-gamedao, and check if squid can work properly when there is no connection to the chain.

```
graph-graph-gamedao-1  | apiProviderResolver error Error: Chain client is not initialized
graph-graph-gamedao-1  |     at Object.apiProviderResolver [as apiProvider] (file:///app/src/resolvers/query/apiProviders/apiProviderResolver.ts:9:10)
graph-graph-gamedao-1  |     at field.resolve (/app/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)
graph-graph-gamedao-1  |     at executeField (/app/node_modules/graphql/execution/execute.js:481:20)
graph-graph-gamedao-1  |     at executeFields (/app/node_modules/graphql/execution/execute.js:413:20)
graph-graph-gamedao-1  |     at executeOperation (/app/node_modules/graphql/execution/execute.js:344:14)
graph-graph-gamedao-1  |     at execute (/app/node_modules/graphql/execution/execute.js:136:20)
graph-graph-gamedao-1  |     at execute (/app/node_modules/apollo-server-core/src/requestPipeline.ts:500:34)
graph-graph-gamedao-1  |     at processGraphQLRequest (/app/node_modules/apollo-server-core/src/requestPipeline.ts:406:28)
graph-graph-gamedao-1  |     at runMicrotasks (<anonymous>)
```

**Comment by 2075** [comment]
eventually a question also for a custom resolver which can return errors / mock data if not available. we build an example here: https://github.com/gamedaoco/gamedao-haiku/issues/441

**Comment by vovacha** [comment]
I guess it's still should be fixed in a fax and simple way and then wait for the mocks to be ready.

**Comment by vovacha** [comment]
Not reproducible. I am moving this issue to Done until it happens again.

**Comment by vovacha** [comment]
It happened again. Moving to the backlog.

**Comment by vovacha** [comment]
PR: https://github.com/gamedaoco/gamedao-haiku/pull/499
